//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WooTable.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WooTable.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DocsPane_but_Cancel {
            get {
                return ResourceManager.GetString("DocsPane_but_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string DocsPane_but_Create {
            get {
                return ResourceManager.GetString("DocsPane_but_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WooTable .::. Currency Converter.
        /// </summary>
        public static string Form_CurrencyConverter {
            get {
                return ResourceManager.GetString("Form_CurrencyConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Form_CurrencyConverter_but_Apply {
            get {
                return ResourceManager.GetString("Form_CurrencyConverter_but_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Form_CurrencyConverter_but_Cancel {
            get {
                return ResourceManager.GetString("Form_CurrencyConverter_but_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion risk coefficient:.
        /// </summary>
        public static string Form_CurrencyConverter_lab_Risk {
            get {
                return ResourceManager.GetString("Form_CurrencyConverter_lab_Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (all values will be incremented by this %).
        /// </summary>
        public static string Form_CurrencyConverter_lab_Riski {
            get {
                return ResourceManager.GetString("Form_CurrencyConverter_lab_Riski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string Form_CurrencyConverter_lab_Riskp {
            get {
                return ResourceManager.GetString("Form_CurrencyConverter_lab_Riskp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source currency:.
        /// </summary>
        public static string Form_CurrencyConverter_lab_Source {
            get {
                return ResourceManager.GetString("Form_CurrencyConverter_lab_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target currency:.
        /// </summary>
        public static string Form_CurrencyConverter_lab_Target {
            get {
                return ResourceManager.GetString("Form_CurrencyConverter_lab_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to:.
        /// </summary>
        public static string Form_CurrencyConverter_lab_To {
            get {
                return ResourceManager.GetString("Form_CurrencyConverter_lab_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WooTable .::. Create New Structural Table.
        /// </summary>
        public static string Form_NewTable {
            get {
                return ResourceManager.GetString("Form_NewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Form_NewTable_but_Cancel {
            get {
                return ResourceManager.GetString("Form_NewTable_but_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Form_NewTable_but_Create {
            get {
                return ResourceManager.GetString("Form_NewTable_but_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string Form_NewTable_group_Dimensions {
            get {
                return ResourceManager.GetString("Form_NewTable_group_Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string Form_NewTable_lab_Columns {
            get {
                return ResourceManager.GetString("Form_NewTable_lab_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string Form_NewTable_lab_Rows {
            get {
                return ResourceManager.GetString("Form_NewTable_lab_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WooTable .::. Set Number Format.
        /// </summary>
        public static string Form_NumberFormat {
            get {
                return ResourceManager.GetString("Form_NumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Form_NumberFormat_but_Apply {
            get {
                return ResourceManager.GetString("Form_NumberFormat_but_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Form_NumberFormat_but_Cancel {
            get {
                return ResourceManager.GetString("Form_NumberFormat_but_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Form_NumberFormat_grid_Formats_1 {
            get {
                return ResourceManager.GetString("Form_NumberFormat_grid_Formats_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Form_NumberFormat_grid_Formats_2 {
            get {
                return ResourceManager.GetString("Form_NumberFormat_grid_Formats_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string Form_NumberFormat_grid_Formats_3 {
            get {
                return ResourceManager.GetString("Form_NumberFormat_grid_Formats_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Form_NumberFormat_grid_Formats_val1 {
            get {
                return ResourceManager.GetString("Form_NumberFormat_grid_Formats_val1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string Form_NumberFormat_grid_Formats_val2 {
            get {
                return ResourceManager.GetString("Form_NumberFormat_grid_Formats_val2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific.
        /// </summary>
        public static string Form_NumberFormat_grid_Formats_val3 {
            get {
                return ResourceManager.GetString("Form_NumberFormat_grid_Formats_val3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom...
        /// </summary>
        public static string Form_NumberFormat_grid_Formats_val4 {
            get {
                return ResourceManager.GetString("Form_NumberFormat_grid_Formats_val4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set format string:.
        /// </summary>
        public static string Form_NumberFormat_lab_Custom {
            get {
                return ResourceManager.GetString("Form_NumberFormat_lab_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a number format or set your own.
        /// </summary>
        public static string Form_NumberFormat_lab_Info {
            get {
                return ResourceManager.GetString("Form_NumberFormat_lab_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WooTable .::. Settings.
        /// </summary>
        public static string Form_Settings {
            get {
                return ResourceManager.GetString("Form_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Form_Settings_but_Apply {
            get {
                return ResourceManager.GetString("Form_Settings_but_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Form_Settings_but_Cancel {
            get {
                return ResourceManager.GetString("Form_Settings_but_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show confirmation dialog when using MIN/MAX/AVG/SUM/MED copy functions.
        /// </summary>
        public static string Form_Settings_check_DialogOnMath {
            get {
                return ResourceManager.GetString("Form_Settings_check_DialogOnMath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Status Bar to show mathematical data on selection.
        /// </summary>
        public static string Form_Settings_check_ModifyStatusBar {
            get {
                return ResourceManager.GetString("Form_Settings_check_ModifyStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export multiline cell as a single cell.
        /// </summary>
        public static string Form_Settings_check_ReplaceNLine {
            get {
                return ResourceManager.GetString("Form_Settings_check_ReplaceNLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show maximum (MAX) value.
        /// </summary>
        public static string Form_Settings_check_ShowMax {
            get {
                return ResourceManager.GetString("Form_Settings_check_ShowMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show median (MED) value.
        /// </summary>
        public static string Form_Settings_check_ShowMedian {
            get {
                return ResourceManager.GetString("Form_Settings_check_ShowMedian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show minimum (MIN) value.
        /// </summary>
        public static string Form_Settings_check_ShowMin {
            get {
                return ResourceManager.GetString("Form_Settings_check_ShowMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency exchange.
        /// </summary>
        public static string Form_Settings_gr_Currency {
            get {
                return ResourceManager.GetString("Form_Settings_gr_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string Form_Settings_gr_Misc {
            get {
                return ResourceManager.GetString("Form_Settings_gr_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle.
        /// </summary>
        public static string Form_Settings_gr_Oracle {
            get {
                return ResourceManager.GetString("Form_Settings_gr_Oracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Bar.
        /// </summary>
        public static string Form_Settings_gr_StatusBar {
            get {
                return ResourceManager.GetString("Form_Settings_gr_StatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string Form_Settings_gr_XLSCopy {
            get {
                return ResourceManager.GetString("Form_Settings_gr_XLSCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates location.
        /// </summary>
        public static string Form_Settings_lab_OracleData {
            get {
                return ResourceManager.GetString("Form_Settings_lab_OracleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Form_Settings_lab_OracleData_Password {
            get {
                return ResourceManager.GetString("Form_Settings_lab_OracleData_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Form_Settings_lab_OracleData_Username {
            get {
                return ResourceManager.GetString("Form_Settings_lab_OracleData_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange ratio provider.
        /// </summary>
        public static string Form_Settings_lab_Provider {
            get {
                return ResourceManager.GetString("Form_Settings_lab_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default conversion risk.
        /// </summary>
        public static string Form_Settings_lab_Ratio {
            get {
                return ResourceManager.GetString("Form_Settings_lab_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string Form_Settings_lab_Ratio2 {
            get {
                return ResourceManager.GetString("Form_Settings_lab_Ratio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: does NOT work for copy of selected range.
        /// </summary>
        public static string Form_Settings_lab_ReplaceNLine {
            get {
                return ResourceManager.GetString("Form_Settings_lab_ReplaceNLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (if disabled, will stop MEDIAN calculation at all).
        /// </summary>
        public static string Form_Settings_lab_ShowMedian {
            get {
                return ResourceManager.GetString("Form_Settings_lab_ShowMedian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Form_Settings_label_lang {
            get {
                return ResourceManager.GetString("Form_Settings_label_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string IconsPane_but_Cancel {
            get {
                return ResourceManager.GetString("IconsPane_but_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string IconsPane_but_Create {
            get {
                return ResourceManager.GetString("IconsPane_but_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Panes_Docs {
            get {
                return ResourceManager.GetString("Panes_Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        public static string Panes_Icons {
            get {
                return ResourceManager.GetString("Panes_Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string Panes_Tables {
            get {
                return ResourceManager.GetString("Panes_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Ribbon_Groups_gr_Main {
            get {
                return ResourceManager.GetString("Ribbon_Groups_gr_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math.
        /// </summary>
        public static string Ribbon_Groups_gr_Math {
            get {
                return ResourceManager.GetString("Ribbon_Groups_gr_Math", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle tools.
        /// </summary>
        public static string Ribbon_Groups_gr_Oracle {
            get {
                return ResourceManager.GetString("Ribbon_Groups_gr_Oracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string Ribbon_Groups_gr_Other {
            get {
                return ResourceManager.GetString("Ribbon_Groups_gr_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Ribbon_Groups_gr_Table {
            get {
                return ResourceManager.GetString("Ribbon_Groups_gr_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WooTable.
        /// </summary>
        public static string Ribbon_Groups_gr_WooTable {
            get {
                return ResourceManager.GetString("Ribbon_Groups_gr_WooTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVG.
        /// </summary>
        public static string Ribbon_Labels_but_WooTable_Avg {
            get {
                return ResourceManager.GetString("Ribbon_Labels_but_WooTable_Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Ribbon_Labels_but_WooTable_Donate {
            get {
                return ResourceManager.GetString("Ribbon_Labels_but_WooTable_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project home.
        /// </summary>
        public static string Ribbon_Labels_but_WooTable_Home {
            get {
                return ResourceManager.GetString("Ribbon_Labels_but_WooTable_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX.
        /// </summary>
        public static string Ribbon_Labels_but_WooTable_Max {
            get {
                return ResourceManager.GetString("Ribbon_Labels_but_WooTable_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MED.
        /// </summary>
        public static string Ribbon_Labels_but_WooTable_Median {
            get {
                return ResourceManager.GetString("Ribbon_Labels_but_WooTable_Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIN.
        /// </summary>
        public static string Ribbon_Labels_but_WooTable_Min {
            get {
                return ResourceManager.GetString("Ribbon_Labels_but_WooTable_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string Ribbon_Labels_but_WooTable_NewTable {
            get {
                return ResourceManager.GetString("Ribbon_Labels_but_WooTable_NewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Ribbon_Labels_but_WooTable_Settings {
            get {
                return ResourceManager.GetString("Ribbon_Labels_but_WooTable_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUM.
        /// </summary>
        public static string Ribbon_Labels_but_WooTable_Sum {
            get {
                return ResourceManager.GetString("Ribbon_Labels_but_WooTable_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell format.
        /// </summary>
        public static string Ribbon_Labels_gal_WooTable_Format {
            get {
                return ResourceManager.GetString("Ribbon_Labels_gal_WooTable_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_Currency {
            get {
                return ResourceManager.GetString("Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float 1 decimal point.
        /// </summary>
        public static string Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_Float1 {
            get {
                return ResourceManager.GetString("Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_Float1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float 2 decimal points.
        /// </summary>
        public static string Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_Float2 {
            get {
                return ResourceManager.GetString("Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_Float2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float 3 decimal points.
        /// </summary>
        public static string Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_Float3 {
            get {
                return ResourceManager.GetString("Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_Float3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float 4 decimal points.
        /// </summary>
        public static string Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_Float4 {
            get {
                return ResourceManager.GetString("Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_Float4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other...
        /// </summary>
        public static string Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_Other {
            get {
                return ResourceManager.GetString("Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_Percent {
            get {
                return ResourceManager.GetString("Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_String {
            get {
                return ResourceManager.GetString("Ribbon_Labels_gal_WooTable_Format_gal_WooTable_but_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert currency.
        /// </summary>
        public static string Ribbon_Labels_sbut_WooTable_ConvCurrency {
            get {
                return ResourceManager.GetString("Ribbon_Labels_sbut_WooTable_ConvCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert currency.
        /// </summary>
        public static string Ribbon_Labels_sbut_WooTable_ConvCurrency_Other {
            get {
                return ResourceManager.GetString("Ribbon_Labels_sbut_WooTable_ConvCurrency_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal separator.
        /// </summary>
        public static string Ribbon_Labels_sbut_WooTable_DecSep {
            get {
                return ResourceManager.GetString("Ribbon_Labels_sbut_WooTable_DecSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format this document.
        /// </summary>
        public static string Ribbon_Labels_sbut_WooTable_Oracle_Format {
            get {
                return ResourceManager.GetString("Ribbon_Labels_sbut_WooTable_Oracle_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        public static string Ribbon_Labels_sbut_WooTable_Oracle_Icons {
            get {
                return ResourceManager.GetString("Ribbon_Labels_sbut_WooTable_Oracle_Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New document.
        /// </summary>
        public static string Ribbon_Labels_sbut_WooTable_Oracle_NewDoc {
            get {
                return ResourceManager.GetString("Ribbon_Labels_sbut_WooTable_Oracle_NewDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To English.
        /// </summary>
        public static string Ribbon_Labels_sbut_WooTable_ToEnglish {
            get {
                return ResourceManager.GetString("Ribbon_Labels_sbut_WooTable_ToEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To English.
        /// </summary>
        public static string Ribbon_Labels_sbut_WooTable_ToEnglish_Other {
            get {
                return ResourceManager.GetString("Ribbon_Labels_sbut_WooTable_ToEnglish_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As currency.
        /// </summary>
        public static string Ribbon_Labels_sbut_WooTable_ToEnglish_Other_sbut_but_WooTable_Other_ToEnglish_Currency {
            get {
                return ResourceManager.GetString("Ribbon_Labels_sbut_WooTable_ToEnglish_Other_sbut_but_WooTable_Other_ToEnglish_Cur" +
                        "rency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As currency.
        /// </summary>
        public static string Ribbon_Labels_sbut_WooTable_ToEnglish_sbut_but_WooTable_ToEnglish_Currency {
            get {
                return ResourceManager.GetString("Ribbon_Labels_sbut_WooTable_ToEnglish_sbut_but_WooTable_ToEnglish_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert tables to Excel.
        /// </summary>
        public static string Ribbon_Labels_sbut_WooTable_XLS1 {
            get {
                return ResourceManager.GetString("Ribbon_Labels_sbut_WooTable_XLS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tables to be converted...
        /// </summary>
        public static string Ribbon_Labels_sbut_WooTable_XLS1_sbut_but_WooTable_XLS1_Select {
            get {
                return ResourceManager.GetString("Ribbon_Labels_sbut_WooTable_XLS1_sbut_but_WooTable_XLS1_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to new XLS.
        /// </summary>
        public static string Ribbon_Labels_tog_WooTable_XLS {
            get {
                return ResourceManager.GetString("Ribbon_Labels_tog_WooTable_XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to opened XLS.
        /// </summary>
        public static string Ribbon_Labels_tog_WooTable_XLS1 {
            get {
                return ResourceManager.GetString("Ribbon_Labels_tog_WooTable_XLS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy AVG of selected values in the table to clipboard.
        /// </summary>
        public static string Ribbon_Tips_but_WooTable_Avg {
            get {
                return ResourceManager.GetString("Ribbon_Tips_but_WooTable_Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking here will redirect you to the project support webpage, where you can easily donate further development using PayPal or direct bank transfer. Thank you for supporting WooTable!.
        /// </summary>
        public static string Ribbon_Tips_but_WooTable_Donate {
            get {
                return ResourceManager.GetString("Ribbon_Tips_but_WooTable_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirects you to the WooTable homepage.
        /// </summary>
        public static string Ribbon_Tips_but_WooTable_Home {
            get {
                return ResourceManager.GetString("Ribbon_Tips_but_WooTable_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy MAX of selected values in the table to clipboard.
        /// </summary>
        public static string Ribbon_Tips_but_WooTable_Max {
            get {
                return ResourceManager.GetString("Ribbon_Tips_but_WooTable_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy MEDIAN of selected values in the table to clipboard.
        /// </summary>
        public static string Ribbon_Tips_but_WooTable_Median {
            get {
                return ResourceManager.GetString("Ribbon_Tips_but_WooTable_Median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy MIN of selected values in the table to clipboard.
        /// </summary>
        public static string Ribbon_Tips_but_WooTable_Min {
            get {
                return ResourceManager.GetString("Ribbon_Tips_but_WooTable_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new structure table (with no borders).
        /// </summary>
        public static string Ribbon_Tips_but_WooTable_NewTable {
            get {
                return ResourceManager.GetString("Ribbon_Tips_but_WooTable_NewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a dialog with WooTable settings and configuration.
        /// </summary>
        public static string Ribbon_Tips_but_WooTable_Settings {
            get {
                return ResourceManager.GetString("Ribbon_Tips_but_WooTable_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy SUM of selected values in the table to clipboard.
        /// </summary>
        public static string Ribbon_Tips_but_WooTable_Sum {
            get {
                return ResourceManager.GetString("Ribbon_Tips_but_WooTable_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert the selected range in a table to a MS Excel table. Make sure to select below if to use the opened or a new MS Excel document.
        /// </summary>
        public static string Ribbon_Tips_but_WooTable_xls1 {
            get {
                return ResourceManager.GetString("Ribbon_Tips_but_WooTable_xls1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert the table in selection to a MS Excel table. Make sure to select below if to use the opened or a new MS Excel document.
        /// </summary>
        public static string Ribbon_Tips_but_WooTable_xls2 {
            get {
                return ResourceManager.GetString("Ribbon_Tips_but_WooTable_xls2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the format of the selected cells. Select numeric cells in a table to use this feature. Note: this feature is stateless - Word will not remember the format you used.
        /// </summary>
        public static string Ribbon_Tips_gal_WooTable_Format {
            get {
                return ResourceManager.GetString("Ribbon_Tips_gal_WooTable_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a dialog for currency conversion. Select range of numeric cells in a word table to enable this feature.
        /// </summary>
        public static string Ribbon_Tips_sbut_WooTable_ConvCurrency {
            get {
                return ResourceManager.GetString("Ribbon_Tips_sbut_WooTable_ConvCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a dialog for currency conversion. Select a number in the text (not in a table) to enable this feature. 
        ///Tip: if you selected a number and the option is not enabled, probably you use incorrect decimal separator (try changing &quot;,&quot; for &quot;.&quot; or vice versa).
        /// </summary>
        public static string Ribbon_Tips_sbut_WooTable_ConvCurrency_Other {
            get {
                return ResourceManager.GetString("Ribbon_Tips_sbut_WooTable_ConvCurrency_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all . and , in numbers with the current culture decimal separator. Select range of cells with numeric values in a table to apply this feature.
        /// </summary>
        public static string Ribbon_Tips_sbut_WooTable_DecSep {
            get {
                return ResourceManager.GetString("Ribbon_Tips_sbut_WooTable_DecSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format this document to Oracle standards.
        /// </summary>
        public static string Ribbon_Tips_sbut_WooTable_Oracle_Format {
            get {
                return ResourceManager.GetString("Ribbon_Tips_sbut_WooTable_Oracle_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Oracle icons.
        /// </summary>
        public static string Ribbon_Tips_sbut_WooTable_Oracle_Icons {
            get {
                return ResourceManager.GetString("Ribbon_Tips_sbut_WooTable_Oracle_Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open selection of available file templates.
        /// </summary>
        public static string Ribbon_Tips_sbut_WooTable_Oracle_NewDoc {
            get {
                return ResourceManager.GetString("Ribbon_Tips_sbut_WooTable_Oracle_NewDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert number to written english. Select cells containing number values in a table to enable this feature.
        /// </summary>
        public static string Ribbon_Tips_sbut_WooTable_ToEnglish {
            get {
                return ResourceManager.GetString("Ribbon_Tips_sbut_WooTable_ToEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert number to written english. Select a number in the text (not in a table) to enable this feature. 
        ///Tip: if you selected a number and the option is not enabled, probably you use incorrect decimal separator (try changing &quot;,&quot; for &quot;.&quot; or vice versa).
        /// </summary>
        public static string Ribbon_Tips_sbut_WooTable_ToEnglish_Other {
            get {
                return ResourceManager.GetString("Ribbon_Tips_sbut_WooTable_ToEnglish_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert all tables in the document to MS Excel.
        /// </summary>
        public static string Ribbon_Tips_sbut_WooTable_XLS1 {
            get {
                return ResourceManager.GetString("Ribbon_Tips_sbut_WooTable_XLS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if the Excel export is done to a new document or to the currently opened document.
        /// </summary>
        public static string Ribbon_Tips_tog_WooTable_XLS {
            get {
                return ResourceManager.GetString("Ribbon_Tips_tog_WooTable_XLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to new XLS.
        /// </summary>
        public static string Ribbons_Labels_tog_WooTable_XLS_1 {
            get {
                return ResourceManager.GetString("Ribbons_Labels_tog_WooTable_XLS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to opened XLS.
        /// </summary>
        public static string Ribbons_Labels_tog_WooTable_XLS_2 {
            get {
                return ResourceManager.GetString("Ribbons_Labels_tog_WooTable_XLS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string TablesPane_but_Apply {
            get {
                return ResourceManager.GetString("TablesPane_but_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TablesPane_but_Cancel {
            get {
                return ResourceManager.GetString("TablesPane_but_Cancel", resourceCulture);
            }
        }
    }
}
